# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33ba155119d3abc72a3127bbccbf29f3ff560897bc73f92d8de1633ea20bba10d7478d43ec20a184be45a469c27f265f63f1b944b6f473ebe30c3537b3dbe514

test:
  secret_key_base: 302da58144e1c623b821ec6fc308bf352a36320287f11b393ab0e57418ffc5c0871fbfc005b7ff9ede77df8ddcb610f9b04444e47e59da558bd3a935ef193cbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
